# Generated by Django 2.2.3 on 2019-07-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
