# Generated by Django 2.2.3 on 2019-07-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt', '0002_auto_20190716_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=35)),
                ('countrycode', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField(default='0')),
            ],
        ),
    ]
