# Generated by Django 2.2.3 on 2019-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt', '0004_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='countrylanguage',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=60)),
                ('isofficial', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
